### ISSUE TITLE
Some auto-generated API documentation is broken

### ISSUE THREAD

**Issue by gbasood** [sharpdx/sharpdx.github.io#6]
![image](https://user-images.githubusercontent.com/2076607/32993115-8be31210-cd08-11e7-893d-523794ec1744.png)
http://sharpdx.org/wiki/class-library-api/direct2d1/#api-Interfaces

**Comment by xoofx** [comment]
Looks like Jekyll broke some stuffs in the meantime

**Comment by dr3adl0rd** [comment]
Wow, it's still broken, just check http://sharpdx.org/wiki/class-library-api/direct3d11/
Such pity, I thought of using SharpDX, but looks like it's not really worth it.

**Comment by xoofx** [comment]
@dr3adl0rd SharpDX is no longer maintained.
